### ISSUE TITLE
Cannot draw in Firefox

### ISSUE THREAD

**Issue by coffeeorgreentea** [gadicc/stable-diffusion-react-nextjs-mui-pwa#38]
Drawing on the canvas in Image to Image and Inpainting does not work in Firefox but does in Chrome

**Comment by gadicc** [comment]
Hey @coffeeorgreentea, thanks so much for reporting this, had no idea!  The fix should be live in about 2m (you might need to force refresh the page to get it to load the new code).

**Comment by gadicc** [comment]
Also if you can send me your email, have some free credits for you as thanks for reporting :)  dragon@wastelands.net
